"""R4-C: emit paper_table_comparison.{md,tex} from *_comparison_agg.parquet files.

Reads output/tables/{ds}_comparison_agg.parquet for all available datasets.
Formats: method | label_T | label_C | T | C | runtime | n_seeds.
Mean +- std to 3 decimal places (quality), 1 decimal (runtime); '--' for NaN.
Rows ordered by label_T desc per dataset (or T desc if unlabeled).
Top-3 cells per metric per dataset tagged \\first / \\second / \\third in TeX.
"""
from __future__ import annotations
import argparse
from pathlib import Path

import numpy as np
import pandas as pd

DATASETS_ORDER = [
    "cora", "citeseer", "pubmed", "mnist_knn", "pbmc", "ca_astroph",
    "coauthor_cs", "coauthor_physics", "ogbn_arxiv",
]
QUALITY_COLS = ["label_trustworthiness", "label_continuity",
                "trustworthiness", "continuity"]
DISPLAY_NAMES = {
    "pysgtsnepi": r"\ours",
    "umap": "UMAP",
    "opentsne": "openTSNE",
    "phate": "PHATE",
    "node2vec_umap": "node2vec+UMAP",
    "drgraph": "DRGraph",
}
RANK_MARKERS = {1: r"\first", 2: r"\second", 3: r"\third"}


def _fmt_q(mean: float, std: float) -> str:
    if np.isnan(mean):
        return "--"
    if np.isnan(std):
        return f"{mean:.3f}"
    return f"{mean:.3f}$\\pm${std:.3f}"


def _fmt_t(mean: float, std: float) -> str:
    if np.isnan(mean):
        return "--"
    if np.isnan(std):
        return f"{mean:.1f}"
    return f"{mean:.1f}$\\pm${std:.1f}"


def _rank_col(series: pd.Series) -> dict[str, int]:
    valid = series.dropna().sort_values(ascending=False)
    return {idx: i + 1 for i, idx in enumerate(valid.index[:3])}


def emit_dataset(ds: str, agg_path: Path) -> tuple[list[str], list[str]]:
    df = pd.read_parquet(agg_path)
    # determine primary sort metric
    has_labels = not df["label_trustworthiness_mean"].isna().all()
    sort_col = "label_trustworthiness_mean" if has_labels else "trustworthiness_mean"
    df = df.sort_values(sort_col, ascending=False).reset_index(drop=True)

    # rank top-3 per metric
    ranks: dict[str, dict] = {}
    for col in ["label_trustworthiness_mean", "trustworthiness_mean"]:
        if col in df.columns:
            ranks[col] = _rank_col(df.set_index("method")[col])

    md_rows, tex_rows = [], []
    for _, row in df.iterrows():
        method = row.get("method", "?")
        name = DISPLAY_NAMES.get(method, method)
        n = int(row.get("n_seeds", 1)) if not np.isnan(row.get("n_seeds", float("nan"))) else 1

        lt_m = row.get("label_trustworthiness_mean", float("nan"))
        lt_s = row.get("label_trustworthiness_std", float("nan"))
        lc_m = row.get("label_continuity_mean", float("nan"))
        lc_s = row.get("label_continuity_std", float("nan"))
        t_m = row.get("trustworthiness_mean", float("nan"))
        t_s = row.get("trustworthiness_std", float("nan"))
        c_m = row.get("continuity_mean", float("nan"))
        c_s = row.get("continuity_std", float("nan"))
        rt_m = row.get("runtime_s_mean", float("nan"))
        rt_s = row.get("runtime_s_std", float("nan"))

        lt_str = _fmt_q(lt_m, lt_s)
        lc_str = _fmt_q(lc_m, lc_s)
        t_str = _fmt_q(t_m, t_s)
        c_str = _fmt_q(c_m, c_s)
        rt_str = _fmt_t(rt_m, rt_s)

        # add rank markers for TeX
        lt_tex = lt_str
        if method in ranks.get("label_trustworthiness_mean", {}):
            r = ranks["label_trustworthiness_mean"][method]
            lt_tex = f"{RANK_MARKERS[r]}{{{lt_str}}}"

        md_rows.append(f"| {name} | {lt_str} | {lc_str} | {t_str} | {c_str} | {rt_str} | {n} |")
        tex_rows.append(
            f"  {name} & {lt_tex} & {lc_str} & {t_str} & {c_str} & {rt_str} & {n} \\\\"
        )

    return md_rows, tex_rows


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out-root", default="output")
    args = p.parse_args()
    out_root = Path(args.out_root)
    tables = out_root / "tables"

    md_lines = ["# Comparison table (auto-generated by emit_paper_table.py)\n"]
    tex_lines = [
        "% comparison table rows (no \\begin{table} wrapper)",
        "% generated by scripts/emit_paper_table.py",
    ]
    header_md = "| Method | label\\_T | label\\_C | T | C | runtime (s) | N |"
    sep_md = "|---|---|---|---|---|---|---|"

    datasets_found = []
    for ds in DATASETS_ORDER:
        agg = tables / f"{ds}_comparison_agg.parquet"
        if agg.exists():
            datasets_found.append(ds)

    for ds in datasets_found:
        md_lines += [f"\n## {ds}\n", header_md, sep_md]
        tex_lines += [f"\n% --- {ds} ---", r"\midrule", f"\\multicolumn{{7}}{{l}}{{\\textit{{{ds}}}}} \\\\"]
        md_rows, tex_rows = emit_dataset(ds, tables / f"{ds}_comparison_agg.parquet")
        md_lines += md_rows
        tex_lines += tex_rows

    md_out = tables / "paper_table_comparison.md"
    tex_out = tables / "paper_table_comparison.tex"
    md_out.write_text("\n".join(md_lines) + "\n")
    tex_out.write_text("\n".join(tex_lines) + "\n")
    print(f"[emit_paper_table] {md_out}  ({len(datasets_found)} datasets)", flush=True)
    print(f"[emit_paper_table] {tex_out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
